-- Run this in your Supabase SQL Editor

-- Create departments table
CREATE TABLE IF NOT EXISTS public.departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT
);

-- Create users table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('CITIZEN', 'DEPT_ADMIN', 'SUPER_ADMIN')),
  department_id BIGINT REFERENCES public.departments(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create complaints table
CREATE TABLE IF NOT EXISTS public.complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  citizen_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  department_id BIGINT NOT NULL REFERENCES public.departments(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT DEFAULT 'PENDING' CHECK(status IN ('PENDING', 'IN_PROGRESS', 'RESOLVED')),
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  image_url TEXT,
  resolution_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create alerts table
CREATE TABLE IF NOT EXISTS public.alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL CHECK(type IN ('EMERGENCY', 'WEATHER', 'TRAFFIC', 'HEALTH')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create jobs table
CREATE TABLE IF NOT EXISTS public.jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  department TEXT NOT NULL,
  description TEXT NOT NULL,
  deadline DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert initial departments
INSERT INTO public.departments (name, description) VALUES
  ('Waste Management', 'Handles city-wide garbage collection and recycling.'),
  ('Transport', 'Manages public transit, roads, and traffic signals.'),
  ('Water & Power', 'Ensures stable supply of water and electricity.'),
  ('Public Safety', 'Police, fire, and emergency response services.')
ON CONFLICT DO NOTHING;

-- Warning: We don't automatically insert the Super Admin here since password hashing 
-- is currently done in Node.js (bcrypt). Make sure to register your admin user via the UI!

-- Create job_applications table
CREATE TABLE IF NOT EXISTS public.job_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  citizen_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  resume_url TEXT NOT NULL,
  status TEXT DEFAULT 'PENDING' CHECK(status IN ('PENDING', 'REVIEWED', 'ACCEPTED', 'REJECTED')),
  applied_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(job_id, citizen_id)
);

-- Add mobile number to users
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS mobile TEXT;


